## Recomendation System For Movies

In [1]:
#libraries 
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv('movies.csv')
users = pd.read_csv('ratings.csv')

In [3]:
movies.head(5)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [4]:
users.head(5)

   userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

In [5]:
#modify the titles to make it easier to perform any NLP operation
#movies = movies.drop_duplicates(subset=['title'])
movies['mod_title']= movies['title'].apply(lambda x: x[:x.find('(')])
movies.head()

,movieId,title,genres,mod_title
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,Toy Story
1,2,Jumanji (1995),Adventure|Children|Fantasy,Jumanji
2,3,Grumpier Old Men (1995),Comedy|Romance,Grumpier Old Men
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,Waiting to Exhale
4,5,Father of the Bride Part II (1995),Comedy,Father of the Bride Part II

In [6]:
movies['mod_title'] = movies['mod_title'].str.lower()

In [7]:
#zero null titles, so we don't need to remove any rows from the dataset
movies['title'].isna().sum()

0

In [8]:
movies[movies['title'].str.contains('Toy')]

,movieId,title,genres,mod_title
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,toy story
1928,2017,Babes in Toyland (1961),Children|Fantasy|Musical,babes in toyland
2162,2253,Toys (1992),Comedy|Fantasy,toys
2993,3086,Babes in Toyland (1934),Children|Comedy|Fantasy|Musical,babes in toyland
3021,3114,Toy Story 2 (1999),Adventure|Animation|Children|Comedy|Fantasy,toy story 2
4823,4929,"Toy, The (1982)",Comedy,"toy, the"
5731,5843,Toy Soldiers (1991),Action|Drama,toy soldiers
8533,26033,Giants and Toys (Kyojin to gangu) (1958),Comedy|Drama,giants and toys
14720,78062,Puppet Master vs. Demonic Toys (Puppet Master ...,Comedy|Fantasy|Horror|Sci-Fi|Thriller,puppet master vs. demonic toys
14813,78499,Toy Story 3 (2010),Adventure|Animation|Children|Comedy|Fantasy|IMAX,toy story 3
15157,80141,"Christmas Toy, The (1986)",Children|Musical,"christmas toy, the"
15559,81981,"Toy, The (Le jouet) (1976)",Comedy,"toy, the"
15834,83439,Toys in the Attic (1963),Drama,toys in the attic
17921,93574,Resurrect Dead: The Mystery of the Toynbee Til...,Documentary|Mystery,resurrect dead: the mystery of the toynbee tiles
20497,106022,Toy Story of Terror (2013),Animation|Children|Comedy,toy story of terror
22633,115875,Toy Story Toons: Hawaiian Vacation (2011),Adventure|Animation|Children|Comedy|Fantasy,toy story toons: hawaiian vacation
22634,115879,Toy Story Toons: Small Fry (2011),Adventure|Animation|Children|Comedy|Fantasy,toy story toons: small fry
22890,116461,How the Toys Saved Christmas (1996),Animation|Children,how the toys saved christmas
23930,119975,"Silent Night, Deadly Night 5: The Toy Maker (1...",Horror|Sci-Fi,"silent night, deadly night 5: the toy maker"
24062,120468,Toy Story Toons: Partysaurus Rex (2012),Animation|Children|Comedy,toy story toons: partysaurus rex
24064,120474,Toy Story That Time Forgot (2014),Animation|Children,toy story that time forgot
24693,122078,The Toy Wife (1938),Drama,the toy wife
25979,124927,Toys in the Attic (2009),Animation|Children|Fantasy|Thriller,toys in the attic
31704,139263,Toy Soldiers (1984),Action|Drama|Thriller,toy soldiers
33224,142663,Babes in Toyland (1997),Animation|Children,babes in toyland
33603,143537,Toy Masters (2014),Documentary,toy masters
36606,150688,Plastic Galaxy: The Story of Star Wars Toys (2...,Documentary,plastic galaxy: the story of star wars toys
37712,153234,Toy Reanimator (2002),Fantasy|Sci-Fi,toy reanimator
40614,159856,The Toy Box (1971),Horror|Sci-Fi,the toy box
43167,165423,Demonic Toys: Personal Demons (2010),Fantasy|Horror,demonic toys: personal demons
46435,172439,Toyland (2007),Drama|War,toyland
47318,174267,Dreams of Toyland (1908),Animation|Drama|Fantasy,dreams of toyland
47539,174765,Soviet Toys (1924),Animation,soviet toys
48438,176651,Time Toys (2017),Children|Sci-Fi,time toys
50990,182187,Broken Toys (1935),Animation,broken toys
51023,182253,Midnight in a Toy Shop (1930),Animation,midnight in a toy shop
54285,189221,The Toymaker (2017),Horror,the toymaker
56004,193227,Sick For Toys (2018),Horror,sick for toys
57295,196047,The Toybox (2018),Horror|Thriller,the toybox
58327,198371,Toy Town Hall (1936),(no genres listed),toy town hall
58832,199484,Toy Gun (2018),Action|Comedy|Crime,toy gun
59767,201588,Toy Story 4 (2019),Adventure|Animation|Children|Comedy,toy story 4
60340,203062,Babes In Toyland (1987),Adventure|Children|Drama|Fantasy,babes in toyland
62160,208112,Rudolph the Red-Nosed Reindeer & the Island of...,Animation|Children,rudolph the red-nosed reindeer & the island of...

In [9]:
#ml packages
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity 
import re

In [10]:
vectorizer = TfidfVectorizer()

tfidf = vectorizer.fit_transform(movies['mod_title'])

In [11]:
query = 'toy story'
processed = re.sub("[^a-zA-Z0-9 ]","", query.lower())
query_vec = vectorizer.transform([processed])
query_vec.toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [12]:
similarity = cosine_similarity(query_vec, tfidf).flatten()
similarity

array([1., 0., 0., ..., 0., 0., 0.])

In [13]:
indices = np.argpartition(similarity,-10)[-5:]
indices

array([ 4823, 14813,  3021, 59767,     0])

In [14]:
results = movies.iloc[indices]
results

,movieId,title,genres,mod_title
4823,4929,"Toy, The (1982)",Comedy,"toy, the"
14813,78499,Toy Story 3 (2010),Adventure|Animation|Children|Comedy|Fantasy|IMAX,toy story 3
3021,3114,Toy Story 2 (1999),Adventure|Animation|Children|Comedy|Fantasy,toy story 2
59767,201588,Toy Story 4 (2019),Adventure|Animation|Children|Comedy,toy story 4
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,toy story

In [15]:
#function that acts as a search engine 
def search(query):
    vectorizer = TfidfVectorizer()

    tfidf = vectorizer.fit_transform(movies['mod_title'])
    
    processed = re.sub("[^a-zA-Z0-9 ]","", query.lower())
    query_vec = vectorizer.transform([processed])
    similarity = cosine_similarity(query_vec, tfidf).flatten()
    
    indices = np.argpartition(similarity,-10)[-5:]
    
    results = movies.iloc[indices]
    
    return results
   
query = 'Toy Story'

search_df = search(query)
search_df

,movieId,title,genres,mod_title
4823,4929,"Toy, The (1982)",Comedy,"toy, the"
14813,78499,Toy Story 3 (2010),Adventure|Animation|Children|Comedy|Fantasy|IMAX,toy story 3
3021,3114,Toy Story 2 (1999),Adventure|Animation|Children|Comedy|Fantasy,toy story 2
59767,201588,Toy Story 4 (2019),Adventure|Animation|Children|Comedy,toy story 4
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,toy story

In [16]:
liked_mov_id = search_df['movieId'].iloc[-1]
liked_mov_id

1

In [17]:
liked_mov_genre = search_df['genres'].iloc[-1]
liked_mov_genre

'Adventure|Animation|Children|Comedy|Fantasy'

In [18]:
users.shape

(25000095, 4)

In [19]:
#get the set of users who also like the same movie as you
overlap_users = set()

for i in range(users.shape[0]):
    
    if users['movieId'].iloc[i] == liked_mov_id and users['rating'].iloc[i] >= 4.5:
        user_id = users['userId'].iloc[i]
        overlap_users.add(user_id)

In [20]:
similar_users = users[users['userId'].isin(overlap_users)]
similar_users

          userId  movieId  rating   timestamp
5101          36        1     5.0   857131378
5102          36        7     3.0   857131397
5103          36       10     3.0   857131163
5104          36       11     4.0   840790432
5105          36       34     5.0   834413787
...          ...      ...     ...         ...
24998887  162533    85774     4.0  1329514173
24998888  162533    88129     4.5  1329514139
24998889  162533    88744     1.5  1329514370
24998890  162533    89470     2.0  1329514353
24998891  162533    90531     3.5  1329514431

[4811582 rows x 4 columns]

In [21]:
merged_df = similar_users.merge(movies,on='movieId',how='inner')
merged_df.head()

,userId,movieId,rating,timestamp,title,genres,mod_title
0,36,1,5.0,857131378,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,toy story
1,75,1,5.0,1537207651,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,toy story
2,86,1,5.0,945462775,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,toy story
3,90,1,5.0,863538043,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,toy story
4,93,1,5.0,1496543050,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,toy story

In [22]:
#look at the movies that have been seen by a fair amount of people 
freq_lst = ((merged_df['mod_title'].value_counts() > 300).apply(lambda x: x if x else np.NaN)).dropna()
freq_names = list(freq_lst.index)
freq_names

['toy story ',
 'forrest gump ',
 'star wars: episode iv - a new hope ',
 'shawshank redemption, the ',
 'pulp fiction ',
 'jurassic park ',
 'matrix, the ',
 'silence of the lambs, the ',
 'star wars: episode vi - return of the jedi ',
 'star wars: episode v - the empire strikes back ',
 'aladdin ',
 'back to the future ',
 'lion king, the ',
 'terminator 2: judgment day ',
 'independence day ',
 'raiders of the lost ark ',
 'braveheart ',
 'toy story 2 ',
 'apollo 13 ',
 'beauty and the beast ',
 "schindler's list ",
 'lord of the rings: the fellowship of the ring, the ',
 'shrek ',
 'fugitive, the ',
 'usual suspects, the ',
 'fargo ',
 'twelve monkeys ',
 'sixth sense, the ',
 'monsters, inc. ',
 'fight club ',
 'seven ',
 'men in black ',
 'lord of the rings: the two towers, the ',
 'batman ',
 'gladiator ',
 'saving private ryan ',
 'groundhog day ',
 'lord of the rings: the return of the king, the ',
 'american beauty ',
 'godfather, the ',
 'finding nemo ',
 'mission: impossible ',
 'princess bride, the ',
 'indiana jones and the last crusade ',
 'true lies ',
 'speed ',
 'terminator, the ',
 'e.t. the extra-terrestrial ',
 'willy wonka & the chocolate factory ',
 'titanic ',
 'die hard ',
 'monty python and the holy grail ',
 'incredibles, the ',
 'ghostbusters ',
 'babe ',
 'twister ',
 'pirates of the caribbean: the curse of the black pearl ',
 'dances with wolves ',
 'mask, the ',
 "bug's life, a ",
 'good will hunting ',
 'ace ventura: pet detective ',
 'alien ',
 'truman show, the ',
 'mrs. doubtfire ',
 'rock, the ',
 'star wars: episode i - the phantom menace ',
 'memento ',
 'dark knight, the ',
 'x-men ',
 'blade runner ',
 "ocean's eleven ",
 'spider-man ',
 "ferris bueller's day off ",
 'fifth element, the ',
 'wizard of oz, the ',
 'aliens ',
 'pretty woman ',
 'batman forever ',
 'batman begins ',
 'die hard: with a vengeance ',
 'dumb & dumber ',
 'home alone ',
 'reservoir dogs ',
 "one flew over the cuckoo's nest ",
 'inception ',
 'goodfellas ',
 "harry potter and the sorcerer's stone ",
 'wall·e ',
 'kill bill: vol. 1 ',
 'jumanji ',
 'minority report ',
 'green mile, the ',
 'beautiful mind, a ',
 'léon: the professional ',
 'up ',
 'stargate ',
 'catch me if you can ',
 'godfather: part ii, the ',
 'ghost ',
 'clueless ',
 'bourne identity, the ',
 'nightmare before christmas, the ',
 'indiana jones and the temple of doom ',
 'jaws ',
 'shining, the ',
 'sleepless in seattle ',
 'being john malkovich ',
 'eternal sunshine of the spotless mind ',
 'goldeneye ',
 'rain man ',
 'breakfast club, the ',
 'crouching tiger, hidden dragon ',
 "there's something about mary ",
 'jerry maguire ',
 'who framed roger rabbit? ',
 'back to the future part ii ',
 '2001: a space odyssey ',
 'austin powers: international man of mystery ',
 'nutty professor, the ',
 'total recall ',
 'cast away ',
 'l.a. confidential ',
 'when harry met sally... ',
 'amelie ',
 'austin powers: the spy who shagged me ',
 'shrek 2 ',
 '101 dalmatians ',
 'clockwork orange, a ',
 'iron man ',
 'big ',
 'stand by me ',
 'planet of the apes ',
 'big lebowski, the ',
 'chicken run ',
 'kill bill: vol. 2 ',
 'edward scissorhands ',
 'birdcage, the ',
 'back to the future part iii ',
 'clear and present danger ',
 'toy story 3 ',
 'as good as it gets ',
 'taxi driver ',
 'clerks ',
 'psycho ',
 'harry potter and the prisoner of azkaban ',
 'waterworld ',
 'spider-man 2 ',
 'dead poets society ',
 'jungle book, the ',
 'shakespeare in love ',
 'interview with the vampire: the vampire chronicles ',
 'snow white and the seven dwarfs ',
 'casablanca ',
 'heat ',
 'ratatouille ',
 'four weddings and a funeral ',
 'harry potter and the chamber of secrets ',
 'beetlejuice ',
 'american history x ',
 'trainspotting ',
 'airplane! ',
 'mummy, the ',
 'american pie ',
 'o brother, where art thou? ',
 'hunt for red october, the ',
 'office space ',
 'happy gilmore ',
 'full metal jacket ',
 'star trek: generations ',
 'dr. strangelove or: how i learned to stop worrying and love the bomb ',
 'armageddon ',
 'star wars: episode ii - attack of the clones ',
 'contact ',
 'star trek: first contact ',
 'apocalypse now ',
 'broken arrow ',
 'x2: x-men united ',
 'avatar ',
 'v for vendetta ',
 'matrix reloaded, the ',
 'donnie darko ',
 'ice age ',
 'little mermaid, the ',
 'outbreak ',
 'get shorty ',
 'liar liar ',
 'meet the parents ',
 'top gun ',
 'blues brothers, the ',
 "mr. holland's opus ",
 "monty python's life of brian ",
 'while you were sleeping ',
 'fish called wanda, a ',
 'life is beautiful ',
 'face/off ',
 'departed, the ',
 'lethal weapon ',
 'mary poppins ',
 'spirited away ',
 'king kong ',
 'casino royale ',
 'avengers, the ',
 'gattaca ',
 'star wars: episode iii - revenge of the sith ',
 'snatch ',
 'ace ventura: when nature calls ',
 'amadeus ',
 'mars attacks! ',
 'crimson tide ',
 'alice in wonderland ',
 'harry potter and the goblet of fire ',
 'santa clause, the ',
 'firm, the ',
 'sin city ',
 'rear window ',
 'net, the ',
 'sabrina ',
 'wallace & gromit: the wrong trousers ',
 'prestige, the ',
 'dead man walking ',
 'bourne supremacy, the ',
 'leaving las vegas ',
 'almost famous ',
 'inglourious basterds ',
 'natural born killers ',
 'shaun of the dead ',
 'lost world: jurassic park, the ',
 'dave ',
 'cliffhanger ',
 'south park: bigger, longer and uncut ',
 'philadelphia ',
 'robocop ',
 'sense and sensibility ',
 'young frankenstein ',
 'mission: impossible ii ',
 'rocky ',
 'mulan ',
 "it's a wonderful life ",
 'dark knight rises, the ',
 'abyss, the ',
 'galaxy quest ',
 'citizen kane ',
 'sound of music, the ',
 'american president, the ',
 'pinocchio ',
 'honey, i shrunk the kids ',
 'juno ',
 'lost in translation ',
 'die hard 2 ',
 'graduate, the ',
 'grease ',
 'little miss sunshine ',
 'bourne ultimatum, the ',
 'few good men, a ',
 'pocahontas ',
 'quiz show ',
 "charlie's angels ",
 'star trek ii: the wrath of khan ',
 'unbreakable ',
 'scream ',
 'raising arizona ',
 'game, the ',
 'eraser ',
 'predator ',
 'big fish ',
 'this is spinal tap ',
 'dogma ',
 'starship troopers ',
 'blair witch project, the ',
 '300 ',
 "pan's labyrinth ",
 'erin brockovich ',
 'i, robot ',
 'interstellar ',
 'matrix revolutions, the ',
 'hunchback of notre dame, the ',
 'fantasia ',
 'sting, the ',
 'close encounters of the third kind ',
 'star trek ',
 'addams family values ',
 'high fidelity ',
 'to kill a mockingbird ',
 'slumdog millionaire ',
 'cinderella ',
 'demolition man ',
 "wayne's world ",
 'untouchables, the ',
 'in the line of fire ',
 "pirates of the caribbean: dead man's chest ",
 'antz ',
 'north by northwest ',
 'lock, stock & two smoking barrels ',
 'maverick ',
 'christmas story, a ',
 'dragonheart ',
 'wallace & gromit: a close shave ',
 'platoon ',
 'superman ',
 'full monty, the ',
 'wedding singer, the ',
 'district 9 ',
 'truth about cats & dogs, the ',
 "what's eating gilbert grape ",
 'school of rock ',
 'pleasantville ',
 'unforgiven ',
 '12 angry men ',
 'air force one ',
 'con air ',
 'hangover, the ',
 'ed wood ',
 'batman returns ',
 'cable guy, the ',
 'iron giant, the ',
 'run lola run ',
 'how to train your dragon ',
 'django unchained ',
 'italian job, the ',
 'good, the bad and the ugly, the ',
 'casino ',
 'butch cassidy and the sundance kid ',
 'requiem for a dream ',
 'my cousin vinny ',
 'bruce almighty ',
 'no country for old men ',
 'grosse pointe blank ',
 'inside out ',
 'ransom ',
 'lady and the tramp ',
 'enemy of the state ',
 'james and the giant peach ',
 'guardians of the galaxy ',
 'crow, the ',
 '40-year-old virgin, the ',
 'men in black ii ',
 'vertigo ',
 'traffic ',
 'patriot, the ',
 'shutter island ',
 'space jam ',
 'last samurai, the ',
 'signs ',
 'royal tenenbaums, the ',
 'harry potter and the order of the phoenix ',
 'chinatown ',
 'spaceballs ',
 'annie hall ',
 'field of dreams ',
 'goonies, the ',
 'peter pan ',
 'harry potter and the half-blood prince ',
 'moulin rouge ',
 'phenomenon ',
 'casper ',
 'mask of zorro, the ',
 'exorcist, the ',
 'hot fuzz ',
 'romancing the stone ',
 'godzilla ',
 'rushmore ',
 '28 days later ',
 'gone with the wind ',
 'harry potter and the deathly hallows: part 1 ',
 'sleepy hollow ',
 'maltese falcon, the ',
 'sherlock holmes ',
 'tombstone ',
 'blazing saddles ',
 'miracle on 34th street ',
 'a.i. artificial intelligence ',
 'city of god ',
 'notting hill ',
 'brazil ',
 'charlie and the chocolate factory ',
 'harry potter and the deathly hallows: part 2 ',
 'fly, the ',
 'kung fu panda ',
 "you've got mail ",
 'judge dredd ',
 "bridget jones's diary ",
 'scarface ',
 'chasing amy ',
 'robin hood: men in tights ',
 'chronicles of narnia: the lion, the witch and the wardrobe, the ',
 'dumbo ',
 'from dusk till dawn ',
 'good morning, vietnam ',
 'rush hour ',
 'zombieland ',
 'father of the bride part ii ',
 'my big fat greek wedding ',
 'rocky horror picture show, the ',
 'english patient, the ',
 'star trek iv: the voyage home ',
 'superbad ',
 'animal house ',
 'lethal weapon 2 ',
 'thomas crown affair, the ',
 'election ',
 'true romance ',
 'alien³ ',
 'children of men ',
 'much ado about nothing ',
 'pianist, the ',
 'i am legend ',
 'three musketeers, the ',
 'legends of the fall ',
 'sneakers ',
 'love actually ',
 'crash ',
 'boogie nights ',
 'hercules ',
 'executive decision ',
 'gremlins ',
 "emperor's new groove, the ",
 'the martian ',
 'million dollar baby ',
 'chocolat ',
 'social network, the ',
 'congo ',
 'rumble in the bronx ',
 'legally blonde ',
 'black hawk down ',
 'grumpier old men ',
 'coneheads ',
 'cape fear ',
 'the hunger games ',
 'the butterfly effect ',
 'karate kid, the ',
 'miss congeniality ',
 'goldfinger ',
 'princess mononoke ',
 'mr. & mrs. smith ',
 '10 things i hate about you ',
 'piano, the ',
 'last action hero ',
 'iron man 2 ',
 'splash ',
 'crocodile dundee ',
 'borat: cultural learnings of america for make benefit glorious nation of kazakhstan ',
 'trading places ',
 'others, the ',
 'glory ',
 'blade ',
 'hook ',
 'desperado ',
 'beverly hills cop ',
 'neverending story, the ',
 "king's speech, the ",
 'league of their own, a ',
 'star wars: episode vii - the force awakens ',
 'dracula ',
 'eyes wide shut ',
 'm*a*s*h ',
 'sling blade ',
 'bambi ',
 'cars ',
 'big hero 6 ',
 'tomorrow never dies ',
 'bad boys ',
 'wolf of wall street, the ',
 'ring, the ',
 'despicable me ',
 'lawrence of arabia ',
 'tommy boy ',
 'birds, the ',
 'zoolander ',
 "the devil's advocate ",
 'army of darkness ',
 'three kings ',
 "singin' in the rain ",
 'girl with the dragon tattoo, the ',
 'last of the mohicans, the ',
 'species ',
 'manchurian candidate, the ',
 'talented mr. ripley, the ',
 'deadpool ',
 'arachnophobia ',
 'wedding crashers ',
 'war of the worlds ',
 'client, the ',
 'thing, the ',
 'wild wild west ',
 'bowling for columbine ',
 'great escape, the ',
 'mad max: fury road ',
 'bridge on the river kwai, the ',
 'time to kill, a ',
 'the imitation game ',
 'serenity ',
 'dirty dancing ',
 'primal fear ',
 'austin powers in goldmember ',
 'naked gun 33 1/3: the final insult ',
 'kick-ass ',
 'hot shots! part deux ',
 "pirates of the caribbean: at world's end ",
 'tarzan ',
 'mummy returns, the ',
 'deep impact ',
 'x-men: first class ',
 'robin hood ',
 'batman & robin ',
 'some like it hot ',
 'scary movie ',
 'dark city ',
 'sleeping beauty ',
 'seven samurai ',
 'watchmen ',
 'highlander ',
 'gran torino ',
 'caddyshack ',
 'x-men: the last stand ',
 'beverly hills cop iii ',
 'witness ',
 'tron ',
 'what women want ',
 'star trek iii: the search for spock ',
 'terminator 3: rise of the machines ',
 'thelma & louise ',
 'cool hand luke ',
 'napoleon dynamite ',
 'remember the titans ',
 'so i married an axe murderer ',
 'heathers ',
 '50 first dates ',
 'transformers ',
 'hudsucker proxy, the ',
 'star trek vi: the undiscovered country ',
 'misery ',
 'illusionist, the ',
 'taken ',
 'jackie brown ',
 'cocoon ',
 "william shakespeare's romeo + juliet ",
 'super size me ',
 'x-files: fight the future, the ',
 'grand day out with wallace and gromit, a ',
 'gravity ',
 'johnny mnemonic ',
 "my best friend's wedding ",
 'best in show ',
 'magnolia ',
 'tin cup ',
 'american psycho ',
 'boot, das ',
 'postman, the ',
 'gone in 60 seconds ',
 "city slickers ii: the legend of curly's gold ",
 'black swan ',
 'aristocats, the ',
 'billy madison ',
 'poltergeist ',
 'chicago ',
 'carrie ',
 'alien: resurrection ',
 'big daddy ',
 'simpsons movie, the ',
 'garden state ',
 'parent trap, the ',
 'perfect storm, the ',
 'pearl harbor ',
 'searching for bobby fischer ',
 'flintstones, the ',
 'hamlet ',
 'lilo & stitch ',
 'river wild, the ',
 'day after tomorrow, the ',
 'grand budapest hotel, the ',
 'edge of tomorrow ',
 'mystic river ',
 'collateral ',
 'kingpin ',
 'hobbit: an unexpected journey, the ',
 'about a boy ',
 'elf ',
 'my fair lady ',
 'mortal kombat ',
 'anchorman: the legend of ron burgundy ',
 'true grit ',
 'training day ',
 'gone girl ',
 'jurassic park iii ',
 'blood diamond ',
 '',
 "bill & ted's excellent adventure ",
 'skyfall ',
 'french kiss ',
 'swingers ',
 'terminal, the ',
 'crying game, the ',
 'hellboy ',
 'whiplash ',
 'sixteen candles ',
 'shanghai noon ',
 'that thing you do! ',
 'adaptation ',
 'tangled ',
 'first knight ',
 'rob roy ',
 'basic instinct ',
 'star trek: the motion picture ',
 'donnie brasco ',
 'african queen, the ',
 'gangs of new york ',
 'national treasure ',
 'labyrinth ',
 'road to perdition ',
 'addams family, the ',
 'mean girls ',
 'american pie 2 ',
 'wag the dog ',
 'ex machina ',
 'say anything... ',
 'little shop of horrors ',
 'willow ',
 'me, myself & irene ',
 'thor ',
 'zootopia ',
 'little women ',
 'wreck-it ralph ',
 "ocean's twelve ",
 'ghostbusters ii ',
 'raging bull ',
 'conspiracy theory ',
 'patriot games ',
 'halloween ',
 'wallace & gromit: the best of aardman animation ',
 'troy ',
 'scott pilgrim vs. the world ',
 'mad max ',
 "howl's moving castle ",
 'stripes ',
 'how the grinch stole christmas ',
 'hotel rwanda ',
 'deer hunter, the ',
 'hero ',
 'nine months ',
 'fast and the furious, the ',
 'curious case of benjamin button, the ',
 "charlotte's web ",
 'dodgeball: a true underdog story ',
 "breakfast at tiffany's ",
 'beavis and butt-head do america ',
 'lethal weapon 3 ',
 'thank you for smoking ',
 'home alone 2: lost in new york ',
 'analyze this ',
 'stranger than fiction ',
 'frozen ',
 'saw ',
 'captain america: the first avenger ',
 'fast times at ridgemont high ',
 'superman ii ',
 'mulholland drive ',
 'west side story ',
 'looper ',
 'spider-man 3 ',
 "hitchhiker's guide to the galaxy, the ",
 'world is not enough, the ',
 'escape from new york ',
 'bowfinger ',
 'nightmare on elm street, a ',
 "muriel's wedding ",
 'naked gun: from the files of police squad!, the ',
 'x-men: days of future past ',
 'moon ',
 'vanilla sky ',
 'brady bunch movie, the ',
 'ben-hur ',
 'lara croft: tomb raider ',
 'hoop dreams ',
 'like water for chocolate ',
 'the lego movie ',
 'captain america: the winter soldier ',
 'godfather: part iii, the ',
 'negotiator, the ',
 'junior ',
 'muppet movie, the ',
 'dawn of the dead ',
 'i.q. ',
 'da vinci code, the ',
 'road warrior, the ',
 'mallrats ',
 'planes, trains & automobiles ',
 'muppet treasure island ',
 'sword in the stone, the ',
 'disclosure ',
 'multiplicity ',
 'there will be blood ',
 'ronin ',
 'pursuit of happyness, the ',
 'knocked up ',
 'prince of egypt, the ',
 'walk the line ',
 'insomnia ',
 'indiana jones and the kingdom of the crystal skull ',
 'panic room ',
 'in bruges ',
 'gandhi ',
 'bend it like beckham ',
 'boondock saints, the ',
 'driving miss daisy ',
 'aviator, the ',
 'ghost in the shell ',
 'the hunger games: catching fire ',
 'old boy ',
 'akira ',
 'iron man 3 ',
 'robin hood: prince of thieves ',
 'hitch ',
 'mighty aphrodite ',
 'risky business ',
 'sister act ',
 'fantastic four ',
 "monty python's the meaning of life ",
 'lethal weapon 4 ',
 'scent of a woman ',
 'day the earth stood still, the ',
 'dazed and confused ',
 'pitch black ',
 'finding neverland ',
 'madagascar ',
 'mystery men ',
 'october sky ',
 'striptease ',
 'source code ',
 'free willy ',
 'her ',
 'kingsman: the secret service ',
 'fahrenheit 9/11 ',
 'tootsie ',
 'time bandits ',
 "knight's tale, a ",
 'fried green tomatoes ',
 'my neighbor totoro ',
 'cool runnings ',
 'rush hour 2 ',
 'sideways ',
 'craft, the ',
 'billy elliot ',
 'frequency ',
 'equilibrium ',
 'nell ',
 'pi ',
 'corpse bride ',
 'limitless ',
 'rise of the planet of the apes ',
 'insider, the ',
 'dark crystal, the ',
 'dune ',
 'tropic thunder ',
 'bonnie and clyde ',
 'gods must be crazy, the ',
 'avengers: age of ultron ',
 'american graffiti ',
 'producers, the ',
 'fear and loathing in las vegas ',
 'wallace & gromit in the curse of the were-rabbit ',
 'jerk, the ',
 'arrival ',
 'star trek: insurrection ',
 'waterboy, the ',
 'father of the bride ',
 'to die for ',
 'lost in space ',
 'sherlock holmes: a game of shadows ',
 'long kiss goodnight, the ',
 'fatal attraction ',
 'cinema paradiso ',
 'night of the living dead ',
 'silver linings playbook ',
 'fisher king, the ',
 'devil wears prada, the ',
 'dr. dolittle ',
 'backdraft ',
 'enemy at the gates ',
 'dr. no ',
 'matilda ',
 'right stuff, the ',
 'dog day afternoon ',
 'hannibal ',
 'adventures of priscilla, queen of the desert, the ',
 'into the wild ',
 'hurt locker, the ',
 'misérables, les ',
 'city slickers ',
 'notebook, the ',
 'american werewolf in london, an ',
 'copycat ',
 'bull durham ',
 "romy and michele's high school reunion ",
 'star trek into darkness ',
 'people vs. larry flynt, the ',
 'brave ',
 'master and commander: the far side of the world ',
 'whole nine yards, the ',
 "national lampoon's vacation ",
 'hancock ',
 'french connection, the ',
 'meet the fockers ',
 'old school ',
 'argo ',
 'hulk ',
 'strange days ',
 'hobbit: the desolation of smaug, the ',
 'inside man ',
 'blue velvet ',
 'freaky friday ',
 'sleepers ',
 'remains of the day, the ',
 'courage under fire ',
 'drive ',
 'patton ',
 'cruel intentions ',
 'star trek v: the final frontier ',
 'runaway bride ',
 'evil dead ii ',
 'elizabeth ',
 'heavy metal ',
 'intouchables ',
 'harold and maude ',
 'jay and silent bob strike back ',
 'christmas vacation ',
 'patch adams ',
 'from russia with love ',
 'l.a. story ',
 'out of sight ',
 'dangerous minds ',
 'player, the ',
 'road trip ',
 'time machine, the ',
 'indian in the cupboard, the ',
 'entrapment ',
 'man on the moon ',
 'anastasia ',
 'specialist, the ',
 'rocketeer, the ',
 'k-pax ',
 'coraline ',
 'emma ',
 'zodiac ',
 'arsenic and old lace ',
 'saint, the ',
 'payback ',
 'lord of war ',
 'teenage mutant ninja turtles ',
 'forgetting sarah marshall ',
 'deliverance ',
 'x-men origins: wolverine ',
 "ocean's thirteen ",
 'awakenings ',
 'fox and the hound, the ',
 'life of pi ',
 'blind side, the  ',
 'femme nikita, la ',
 'daredevil ',
 'strictly ballroom ',
 'manhattan ',
 'go ',
 'conan the barbarian ',
 'jfk ',
 'blow ',
 '¡three amigos! ',
 "rosemary's baby ",
 'team america: world police ',
 'constantine ',
 'don juan demarco ',
 'megamind ',
 'escape from l.a. ',
 'moonstruck ',
 'pretty in pink ',
 'hollow man ',
 'shine ',
 'stuart little ',
 'rudy ',
 'waking ned devine ',
 'first blood ',
 'final fantasy: the spirits within ',
 'the count of monte cristo ',
 'never been kissed ',
 'night at the museum ',
 'life aquatic with steve zissou, the ',
 'amazing spider-man, the ',
 'frighteners, the ',
 'burn after reading ',
 'scream 2 ',
 'scrooged ',
 'lucky number slevin ',
 'phone booth ',
 'cell, the ',
 'man on fire ',
 'quantum of solace ',
 '3:10 to yuma ',
 'moonrise kingdom ',
 'rogue one: a star wars story ',
 'die another day ',
 '21 jump street ',
 'brokeback mountain ',
 'ant-man ',
 'what about bob? ',
 'bullets over broadway ',
 'running man, the ',

In [23]:
common_liked = merged_df[merged_df['mod_title'].isin(freq_names)]
common_liked['mod_genre'] = common_liked['genres'].str.replace('[|]'," ", regex=True)
common_liked

/var/folders/r3/mc3pdgtj3rn3d0pd71phd8540000gr/T/ipykernel_99818/1977826254.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  common_liked['mod_genre'] = common_liked['genres'].str.replace('[|]'," ", regex=True)

,userId,movieId,rating,timestamp,title,genres,mod_title,mod_genre
0,36,1,5.0,857131378,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,toy story,Adventure Animation Children Comedy Fantasy
1,75,1,5.0,1537207651,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,toy story,Adventure Animation Children Comedy Fantasy
2,86,1,5.0,945462775,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,toy story,Adventure Animation Children Comedy Fantasy
3,90,1,5.0,863538043,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,toy story,Adventure Animation Children Comedy Fantasy
4,93,1,5.0,1496543050,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,toy story,Adventure Animation Children Comedy Fantasy
...,...,...,...,...,...,...,...,...
4810970,152653,135745,1.5,1440608023,Labyrinth (2012),Adventure|Fantasy,labyrinth,Adventure Fantasy
4811128,154484,187265,3.5,1524881814,The Accountant (2001),Comedy|Drama,the accountant,Comedy Drama
4811159,154484,187431,2.0,1524930699,Bad Company (1999),Drama|Romance,bad company,Drama Romance
4811266,155163,175433,4.0,1500204900,Get Out (2010),Animation|Comedy,get out,Animation Comedy
4811293,155504,206899,3.5,1574045031,Charlie's Angels (2019),Action|Adventure|Comedy,charlie's angels,Action Adventure Comedy

In [24]:
most_liked = common_liked.groupby('mod_title').mean()[['rating']].sort_values('rating',ascending=False).\
reset_index()
most_liked

                                     mod_title    rating
0                                   toy story   4.858535
1                                planet earth   4.618056
2                   shawshank redemption, the   4.589576
3                            schindler's list   4.474211
4                              godfather, the   4.459941
...                                        ...       ...
3010       police academy 6: city under siege   1.863260
3011                                 catwoman   1.804772
3012                            baby geniuses   1.735905
3013  dumb and dumberer: when harry met lloyd   1.705634
3014                        battlefield earth   1.537084

[3015 rows x 2 columns]

In [25]:
#the ratings seem to be more popularity-based, we need to make it more niche -> use genres to filter

In [26]:
genres_movies = common_liked[['mod_title','mod_genre']].drop_duplicates(subset=['mod_title'])
genres_movies

                        mod_title                                    mod_genre
0                      toy story   Adventure Animation Children Comedy Fantasy
18835                    sabrina                                Comedy Romance
21375                  goldeneye                     Action Adventure Thriller
26224    american president, the                          Comedy Drama Romance
29514                       babe                                Children Drama
...                           ...                                          ...
4597180              crazy heart                                 Drama Romance
4599529          little children                                 Drama Romance
4609196                rocketman                                         Drama
4609541               swing kids                                     Drama War
4668079             getaway, the                   Action Crime Drama Thriller

[3015 rows x 2 columns]

In [27]:
general_rec_df = most_liked.merge(genres_movies, on='mod_title')
general_rec_df

,mod_title,rating,mod_genre
0,toy story,4.858535,Adventure Animation Children Comedy Fantasy
1,planet earth,4.618056,Documentary
2,"shawshank redemption, the",4.589576,Crime Drama
3,schindler's list,4.474211,Drama War
4,"godfather, the",4.459941,Crime Drama
...,...,...,...
3010,police academy 6: city under siege,1.863260,Comedy Crime
3011,catwoman,1.804772,Action Crime Fantasy
3012,baby geniuses,1.735905,Comedy
3013,dumb and dumberer: when harry met lloyd,1.705634,Comedy
3014,battlefield earth,1.537084,Action Sci-Fi

In [28]:
vectorizer2 = TfidfVectorizer()

tfidf2 = vectorizer2.fit_transform(general_rec_df['mod_genre'])

In [29]:
query_genre = 'Adventure|Animation|Children|Comedy|Fantasy'
processed2 = re.sub("[|]"," ", query_genre)
processed2

'Adventure Animation Children Comedy Fantasy'

In [30]:
query_vec2 = vectorizer2.transform([processed2])
similarity2 = cosine_similarity(query_vec2, tfidf2).flatten()
similarity2

array([1.        , 0.        , 0.        , ..., 0.28763292, 0.28763292,
       0.        ])

In [31]:
indices2 = np.argpartition(similarity2,-10)[-50:]
indices2

array([1537, 2467, 2228, 2581,   79, 1788, 2200, 1850, 1737,  779, 2329,
        542, 1008,   68,   47,   26,  655, 1795, 1920, 2379, 1449,  518,
         41, 1744, 1955, 2289, 1592, 2620,  174,  433,  987,  412, 1664,
        557,  226,  158, 1657, 2238, 2208, 1488,   70, 2042, 2973,   12,
        320, 2444,   43, 1684,  749,    0])

In [32]:
recs_df = general_rec_df.iloc[indices2].sort_values('rating',ascending=False)
final_df = recs_df.iloc[1:11]
rec_lst = list(final_df['mod_title'])
rec_lst

['toy story 2 ',
 'spirited away ',
 'finding nemo ',
 'monsters, inc. ',
 'my neighbor totoro ',
 'incredibles, the ',
 'inside out ',
 'coco ',
 "kiki's delivery service ",
 'partly cloudy ']

In [33]:
#put the all above steps into a function with only 2 parameters (generated by previous function)
def suggested_lst(mov_ID,mov_genre): 
    overlap_users = set()

    for i in range(users.shape[0]):
    
        if users['movieId'].iloc[i] == mov_ID and users['rating'].iloc[i] >= 4.5:
            user_id = users['userId'].iloc[i]
            overlap_users.add(user_id)
            
    similar_users = users[users['userId'].isin(overlap_users)]
    merged_df = similar_users.merge(movies,on='movieId',how='inner')
    
    
    freq_lst = ((merged_df['mod_title'].value_counts() > 30).apply(lambda x: x if x else np.NaN)).dropna()
    freq_names = list(freq_lst.index)
    
    if (len(freq_names)==0):
        return []
    
    common_liked = merged_df[merged_df['mod_title'].isin(freq_names)]
    common_liked['mod_genre'] = common_liked['genres'].str.replace('[|]'," ", regex=True)
    
    most_liked = common_liked.groupby('mod_title').mean()[['rating']].sort_values('rating',ascending=False).\
    reset_index()
    
    genres_movies = common_liked[['mod_title','mod_genre']].drop_duplicates(subset=['mod_title'])
    
    general_rec_df = most_liked.merge(genres_movies, on='mod_title')
    
    vectorizer2 = TfidfVectorizer()
    tfidf2 = vectorizer2.fit_transform(general_rec_df['mod_genre'])
    
    query_genre = mov_genre
    processed2 = re.sub("[|]"," ", query_genre)
    
    query_vec2 = vectorizer2.transform([processed2])
    similarity2 = cosine_similarity(query_vec2, tfidf2).flatten()
    indices2 = np.argpartition(similarity2,-10)[-50:]
    
    recs_df = general_rec_df.iloc[indices2].sort_values('rating',ascending=False)
    final_df = recs_df.iloc[1:11]
    rec_lst = list(final_df['mod_title'])
    
    
    return rec_lst

In [34]:
#suggested_lst(liked_mov_id,liked_mov_genre)

In [37]:
def model(query):
    
    search_df = search(query)
    
    liked_mov_id = search_df['movieId'].iloc[-1]
    
    liked_mov_genre = search_df['genres'].iloc[-1]
    
    ans = suggested_lst(liked_mov_id, liked_mov_genre)
    
    return ans

In [38]:
model("Toy Story")

/var/folders/r3/mc3pdgtj3rn3d0pd71phd8540000gr/T/ipykernel_99818/1504509142.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  common_liked['mod_genre'] = common_liked['genres'].str.replace('[|]'," ", regex=True)

['toy story 2 ',
 'spirited away ',
 'finding nemo ',
 'monsters, inc. ',
 'my neighbor totoro ',
 'incredibles, the ',
 'inside out ',
 'coco ',
 "kiki's delivery service ",
 'partly cloudy ']

In [57]:
functions = {'func1':search, 'func2':suggested_lst, 'func3':model}

In [58]:
import os 
import pickle

In [59]:
current = os.getcwd()
current

'/Users/u71072/Desktop/Rec_System'

In [60]:
model_fp = os.path.join(current,"model")
os.makedirs(model_fp, exist_ok=True)
model_file = os.path.join(model_fp, "model.pkl")
with open(model_file, "wb") as f:
    pickle.dump(functions, f)

- Pickle does not seem to deserialize without error in the .py file that will hold the code for the website
- For the time being, the functions had to be transferred over to a newly .py file that contains the definitions of the functions we have been using, and we imported that file into the .py file of the website.